version: "3.8"
services:
  # Frontend React Application
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    depends_on:
      - server

  # Backend Flask Application
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 4000:4000
