version: "3.8"
services:
  frontend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
      - ./node_modules
    depends_on:
      - server

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
