version: "3.8"
services:
  client:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 4000:4000
